python ResNet152V2_model_processor_lists.py --set 1 --run 1 --dir .\image_data
python ResNet152V2_model_processor_lists.py --set 1 --run 2 --dir .\image_data
python ResNet152V2_model_processor_lists.py --set 1 --run 3 --dir .\image_data
python ResNet152V2_model_processor_lists.py --set 2 --run 1 --dir .\image_data
python ResNet152V2_model_processor_lists.py --set 2 --run 2 --dir .\image_data
python ResNet152V2_model_processor_lists.py --set 2 --run 3 --dir .\image_data
python ResNet152V2_model_processor_lists.py --set 3 --run 1 --dir .\image_data
python ResNet152V2_model_processor_lists.py --set 3 --run 2 --dir .\image_data
python ResNet152V2_model_processor_lists.py --set 3 --run 3 --dir .\image_data
python ResNet152V2_model_processor_lists.py --set 4 --run 1 --dir .\image_data
python ResNet152V2_model_processor_lists.py --set 4 --run 2 --dir .\image_data
python ResNet152V2_model_processor_lists.py --set 4 --run 3 --dir .\image_data
python ResNet152V2_model_processor_lists.py --set 5 --run 1 --dir .\image_data
python ResNet152V2_model_processor_lists.py --set 5 --run 2 --dir .\image_data
python ResNet152V2_model_processor_lists.py --set 5 --run 3 --dir .\image_data