// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzuJhM_EuZfDXlBepa3H7GJFsoBXGfpF0',
    appId: '1:906930916105:web:58a37d0ae4aff18e89e1d8',
    messagingSenderId: '906930916105',
    projectId: 'craft-40cda',
    authDomain: 'craft-40cda.firebaseapp.com',
    storageBucket: 'craft-40cda.appspot.com',
    measurementId: 'G-RPVFC3WPSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv9i9m95XjsXAZPWYPZMJTlx_0u9GEHIA',
    appId: '1:906930916105:android:1f71a95b40a0428989e1d8',
    messagingSenderId: '906930916105',
    projectId: 'craft-40cda',
    storageBucket: 'craft-40cda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKv2tzQq-gwF_EEUzCDdihCPH10dDQZyI',
    appId: '1:906930916105:ios:7250879302a6349c89e1d8',
    messagingSenderId: '906930916105',
    projectId: 'craft-40cda',
    storageBucket: 'craft-40cda.appspot.com',
    iosBundleId: 'com.example.craft',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzuJhM_EuZfDXlBepa3H7GJFsoBXGfpF0',
    appId: '1:906930916105:web:9fa37010da9bdd4889e1d8',
    messagingSenderId: '906930916105',
    projectId: 'craft-40cda',
    authDomain: 'craft-40cda.firebaseapp.com',
    storageBucket: 'craft-40cda.appspot.com',
    measurementId: 'G-03KHH02SW7',
  );
}
